# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/19NOFjeqQ8YabOg74RalIvTUuNu7uEfIr
"""

x=5
print("變數x的值是:", x)
print("變數x的記憶體地址是:",id(x))

