# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ug7ZTQfniTOn2k322R1HiUqH-TbPmua7
"""

a=int(input())
b=int(input())
c=int(input())
page_table = {0: a, 1: b, 2: c}
page_size = 4096
logical_address = int(input())
memory_addressing(page_table, page_size, logical_address)
def memory_addressing(page_table, page_size,logical_address):
  page_number, offset = divmod(logical_address, page_size)

  if page_number in page_table:
    frame_number = page_table[page_number]
    physical_address = frame_number * page_size + offset
    print(f"The physical address is {physical_address}")
  else:
    print("Invalid page number, address translation failed.")